=== Zeracronius/DynamicTradeInterface/1.4/Schemas/TradeColumnDef.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
	<xs:element name="Defs">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="DynamicTradeInterface.Defs.TradeColumnDef" type="TradeColumnDef" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="SortDirection">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Ascending" />
			<xs:enumeration value="Descending" />
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="TradeColumnDef">
		<xs:all>
			<xs:element name="defName" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="label" type="xs:string" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>
						Text used for column header when column is displayed.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="description"  type="xs:string" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>
						Shown as a tooltip in column selection.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="callbackHandler" type="xs:string" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>
						Colon-based method identifier string for method called when column is drawn.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="orderValueCallbackHandler" type="xs:string" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>
						Colon-based method identifier string for method to allow rows to be sorted by this column.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="searchValueCallbackHandler" type="xs:string" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>
						Colon-based method identifier string for method to allow this column to provide rows with additional searchable strings.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="postOpenCallbackHandler" type="xs:string" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>
						Colon-based method identifier string for method called right after the trade window has been opened. Can be used to cache data.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="postClosedCallbackHandler" type="xs:string" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>
						Colon-based method identifier string for method called right after the trade window has been closed. Can be used to clean up cached data.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="defaultWidth" type="xs:float" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>
						Width of the column. Default is 100.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="defaultVisible" type="xs:boolean" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>
						Whether or not the column should be automatically added to visible columns.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="showCaption" type="xs:boolean" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>
						Whether the label should be shown in the column header.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="tooltip" type="xs:string" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>
						If set then this is shown as a tooltip on column header, otherwise label is used.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="initialSort" type="SortDirection" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>
						The direction the column will sort by on first click. Descending is default.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:all>
	</xs:complexType>
</xs:schema>

=== Zeracronius/DynamicTradeInterface/1.5/Defs/ColumnDefs.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../Schemas/TradeColumnDef.xsd">
	<DynamicTradeInterface.Defs.TradeColumnDef>
		<defName>colTradeIconDef</defName>
		<label>icon</label>
		<description>A small image of what you are trading.</description>
		<showCaption>false</showCaption>
		<callbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnIcon:Draw</callbackHandler>
		<defaultWidth>40</defaultWidth>
	</DynamicTradeInterface.Defs.TradeColumnDef>

	<DynamicTradeInterface.Defs.TradeColumnDef>
		<defName>colTradeInfoDef</defName>
		<label></label>
		<tooltip>info button</tooltip>
		<description>Button to open the info window.</description>
		<showCaption>false</showCaption>
		<callbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnInfo:Draw</callbackHandler>
		<postOpenCallbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnInfo:PostOpen</postOpenCallbackHandler>
		<postClosedCallbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnInfo:PostClosed</postClosedCallbackHandler>
		<defaultWidth>20</defaultWidth>
	</DynamicTradeInterface.Defs.TradeColumnDef>

	<DynamicTradeInterface.Defs.TradeColumnDef>
		<defName>colTradeCaptionDef</defName>
		<label>caption</label>
		<description>Shows the name.</description>
		<callbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnCaption:Draw</callbackHandler>
		<orderValueCallbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnCaption:OrderbyValue</orderValueCallbackHandler>
		<postOpenCallbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnCaption:PostOpen</postOpenCallbackHandler>
		<postClosedCallbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnCaption:PostClosed</postClosedCallbackHandler>
		<initialSort>Ascending</initialSort>
		<defaultWidth>1</defaultWidth>
	</DynamicTradeInterface.Defs.TradeColumnDef>

	<DynamicTradeInterface.Defs.TradeColumnDef>
		<defName>colTradeExtraIconsDef</defName>
		<label>extra icons</label>
		<description>Additional icons shown in different situations.</description>
		<showCaption>false</showCaption>
		<callbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnExtraIcons:Draw</callbackHandler>
		<searchValueCallbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnExtraIcons:SearchValue</searchValueCallbackHandler>
		<postOpenCallbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnExtraIcons:PostOpen</postOpenCallbackHandler>
		<postClosedCallbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnExtraIcons:PostClosed</postClosedCallbackHandler>
		<defaultWidth>50</defaultWidth>
	</DynamicTradeInterface.Defs.TradeColumnDef>

	<DynamicTradeInterface.Defs.TradeColumnDef>
		<defName>colTradeQuantityDef</defName>
		<label>available</label>
		<description>Quantity available for buying or selling.</description>
		<callbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnQuantity:Draw</callbackHandler>
		<orderValueCallbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnQuantity:OrderbyValue</orderValueCallbackHandler>
		<defaultWidth>75</defaultWidth>
	</DynamicTradeInterface.Defs.TradeColumnDef>

	<DynamicTradeInterface.Defs.TradeColumnDef>
		<defName>colTradePriceDef</defName>
		<label>price</label>
		<description>Shows the price.</description>
		<callbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnPrice:Draw</callbackHandler>
		<orderValueCallbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnPrice:OrderbyValue</orderValueCallbackHandler>
		<postOpenCallbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnPrice:PostOpen</postOpenCallbackHandler>
		<postClosedCallbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnPrice:PostClosed</postClosedCallbackHandler>
		<defaultWidth>75</defaultWidth>
	</DynamicTradeInterface.Defs.TradeColumnDef>

	<DynamicTradeInterface.Defs.TradeColumnDef>
		<defName>colTradeCounterDef</defName>
		<label>counter box</label>
		<description>Numeric box where the current quantity bought or sold is shown and can be entered manually.</description>
		<showCaption>false</showCaption>
		<callbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnCounter:Draw</callbackHandler>
		<orderValueCallbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnCounter:OrderbyValue</orderValueCallbackHandler>
		<postOpenCallbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnCounter:PostOpen</postOpenCallbackHandler>
		<postClosedCallbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnCounter:PostClosed</postClosedCallbackHandler>
		<defaultWidth>80</defaultWidth>
	</DynamicTradeInterface.Defs.TradeColumnDef>

	<DynamicTradeInterface.Defs.TradeColumnDef>
		<defName>colTradeButtonsDef</defName>
		<label>buttons</label>
		<showCaption>true</showCaption>
		<description>Buttons used to increment or decrement the amount bought or sold.\nClicking the double arrow buttons will increase to most affordable by either party on first click and then to max quantity if clicked again. Hold shift to skip.</description>
		<callbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnButtons:Draw</callbackHandler>
		<postOpenCallbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnButtons:PostOpen</postOpenCallbackHandler>
		<postClosedCallbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnButtons:PostClosed</postClosedCallbackHandler>
		<defaultWidth>90</defaultWidth>
	</DynamicTradeInterface.Defs.TradeColumnDef>
</Defs>

=== Zeracronius/DynamicTradeInterface/1.4/Defs/OptionalColumns.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../Schemas/TradeColumnDef.xsd">
	<DynamicTradeInterface.Defs.TradeColumnDef>
		<defName>colDurabilityDef</defName>
		<label>d</label>
		<tooltip>Durability</tooltip>
		<description>Shows the remaining hitpoints (if any) as a percentage.</description>
		<defaultWidth>40</defaultWidth>
		<defaultVisible>false</defaultVisible>
		<callbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnDurability:Draw</callbackHandler>
		<orderValueCallbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnDurability:OrderbyValue</orderValueCallbackHandler>
	</DynamicTradeInterface.Defs.TradeColumnDef>

	<DynamicTradeInterface.Defs.TradeColumnDef>
		<defName>colPricePerWeightDef</defName>
		<label>/kg</label>
		<tooltip>price / kg</tooltip>
		<description>Shows the price divided by mass.</description>
		<defaultWidth>50</defaultWidth>
		<defaultVisible>false</defaultVisible>
		<callbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnPricePerWeight:Draw</callbackHandler>
		<orderValueCallbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnPricePerWeight:OrderbyValue</orderValueCallbackHandler>
		<postOpenCallbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnPricePerWeight:PostOpen</postOpenCallbackHandler>
		<postClosedCallbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnPricePerWeight:PostClosed</postClosedCallbackHandler>
	</DynamicTradeInterface.Defs.TradeColumnDef>
</Defs>

=== Zeracronius/DynamicTradeInterface/1.5/Defs/OptionalColumns.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../Schemas/TradeColumnDef.xsd">
	<DynamicTradeInterface.Defs.TradeColumnDef>
		<defName>colDurabilityDef</defName>
		<label>d</label>
		<tooltip>Durability</tooltip>
		<description>Shows the remaining hitpoints (if any) as a percentage.</description>
		<defaultWidth>40</defaultWidth>
		<defaultVisible>false</defaultVisible>
		<postClosedCallbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnDurability:PostClosed</postClosedCallbackHandler>
		<postOpenCallbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnDurability:PostOpen</postOpenCallbackHandler>
		<callbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnDurability:Draw</callbackHandler>
		<orderValueCallbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnDurability:OrderbyValue</orderValueCallbackHandler>
	</DynamicTradeInterface.Defs.TradeColumnDef>

	<DynamicTradeInterface.Defs.TradeColumnDef>
		<defName>colPricePerWeightDef</defName>
		<label>/kg</label>
		<tooltip>price / kg</tooltip>
		<description>Shows the price divided by mass.</description>
		<defaultWidth>50</defaultWidth>
		<defaultVisible>false</defaultVisible>
		<callbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnPricePerWeight:Draw</callbackHandler>
		<orderValueCallbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnPricePerWeight:OrderbyValue</orderValueCallbackHandler>
		<postOpenCallbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnPricePerWeight:PostOpen</postOpenCallbackHandler>
		<postClosedCallbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnPricePerWeight:PostClosed</postClosedCallbackHandler>
	</DynamicTradeInterface.Defs.TradeColumnDef>

	<DynamicTradeInterface.Defs.TradeColumnDef>
		<defName>colTradeCounterLabelDef</defName>
		<label>counter box</label>
		<description>A faster read-only version of the counter box where the current quantity bought or sold is shown.</description>
		<showCaption>false</showCaption>
		<defaultVisible>false</defaultVisible>
		<callbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnCounterLabel:Draw</callbackHandler>
		<orderValueCallbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnCounterLabel:OrderbyValue</orderValueCallbackHandler>
		<postOpenCallbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnCounterLabel:PostOpen</postOpenCallbackHandler>
		<postClosedCallbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnCounterLabel:PostClosed</postClosedCallbackHandler>
		<defaultWidth>80</defaultWidth>
	</DynamicTradeInterface.Defs.TradeColumnDef>

	<DynamicTradeInterface.Defs.TradeColumnDef>
		<defName>colCategoryDef</defName>
		<label>category</label>
		<description>Shows the main category of the thing.</description>
		<showCaption>true</showCaption>
		<defaultVisible>false</defaultVisible>
		<callbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnCategory:Draw</callbackHandler>
		<orderValueCallbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnCategory:OrderbyValue</orderValueCallbackHandler>
		<searchValueCallbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnCategory:SearchValue</searchValueCallbackHandler>
		<postOpenCallbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnCategory:PostOpen</postOpenCallbackHandler>
		<postClosedCallbackHandler>DynamicTradeInterface.UserInterface.Columns.ColumnCategory:PostClosed</postClosedCallbackHandler>
		<defaultWidth>80</defaultWidth>
	</DynamicTradeInterface.Defs.TradeColumnDef>
</Defs>
